name: Custom build
on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "The name that will be displayed on your app"
        required: false
        default: "My awesome app"
      enable_paragraph:
        description: "Show paragraph on home page"
        required: false
        default: "1"

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          export VITE_APP_NAME
          export VITE_ENABLE_PARAGRAPH
          npm run build
        env:
          VITE_APP_NAME: ${{ github.event.inputs.app_name }}
          VITE_ENABLE_PARAGRAPH: ${{ github.event.inputs.enable_paragraph }}

      - uses: actions/upload-artifact@v3
        with:
          name: statics
          path: dist/
